# Generated by Django 5.1.15 on 2026-05-04 14:00

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='body',
            field=core.fields.MarkdownField(help_text='(Markdown)'),
        ),
    ]
