# Generated by Django 5.1.15 on 2026-05-04 13:17

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='title',
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_prompt',
            field=core.fields.MarkdownField(blank=True, help_text='Initial brief / prompt for the project (Markdown).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='launch_specs',
            field=core.fields.MarkdownField(blank=True, help_text='Launch specifications (Markdown).'),
        ),
    ]
