# Generated by Django 5.1.15 on 2026-05-04 14:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_remove_objective_title_alter_objective_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=core.fields.MarkdownField(blank=True, help_text='(Markdown)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=core.fields.MarkdownField(help_text='(Markdown)'),
        ),
    ]
