# Generated by Django 5.1.15 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_client_email_client_phone_alter_client_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('todo', 'Future'), ('in_progress', 'Open'), ('blocked', 'Backlog'), ('done', 'Closed')], default='todo', max_length=20),
        ),
    ]
