# Generated by Django 5.1.15 on 2026-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_objective_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this project (and everything inside it) from guest users.'),
        ),
    ]
